# ~/viva/docker-compose.yml
version: '3'
services:
  frontend:
    build: ./viva-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - viva-network

  backend:
    build: ./viva-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - viva-network

networks:
  viva-network:
    driver: bridge

