# ~/viva/docker-compose.yml
version: '3'
services:
  frontend:
    build: ./viva-frontend
    image: louisleonard/viva-frontend:${TAG:-latest}
    ports:
      - "80:80"
      - "443:443"  # 添加这行
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # 添加这行
    depends_on:
      - backend
    networks:
      - viva-network

  backend:
    build: 
      context: ./viva-backend
      dockerfile: Dockerfile
    image: louisleonard/viva-backend:${TAG:-latest}
    volumes:
      - ./viva-backend/.env:/app/viva-backend/.env  # 映射到容器内相同的相对路径
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=postgresql://user:password@db:5432/viva_db  # 添加数据库URL
    depends_on:
      - db
    networks:
      - viva-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=viva_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - viva-network

networks:
  viva-network:
    driver: bridge

volumes:
  postgres_data: