# ~/viva/docker-compose.yml
version: '3'
services:
  frontend:
    build: ./viva-frontend
    image: louisleonard/viva-frontend:${TAG:-latest}
    ports:
      - "80:80"
      - "443:443"  # 添加这行
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # 添加这行
    depends_on:
      - backend
    networks:
      - viva-network

  backend:
    build: 
      context: ./viva-backend
      dockerfile: Dockerfile
    image: louisleonard/viva-backend:${TAG:-latest}
    volumes:
      - ./viva-backend/.env:/app/.env  # 把.env里的api key 挂载进容器中,因为这些 key 无法通过 github 传送
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - viva-network


networks:
  viva-network:
    driver: bridge

volumes:
  postgres_data: