name: Deploy Viva Project

on:
  push:
    branches:
      - main          # 生产环境部署
  # pull_request:       # 添加 PR 触发器
  #   branches:
  #     - main

jobs:
  test:   # 自动化测试的内容（现在写了个必过的，以后再优化）
    runs-on: ubuntu-latest
    steps:
      - name: Always pass
        run: echo "Tests passed successfully!"
          
  deploy:
    needs: test       # 需要先跑自动化测试
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

#      - name: Install Docker Compose
#        uses: ndeloof/install-compose-action@v0.0.1
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push Docker images
#        run: |
#          docker-compose build
#          docker-compose push
#
#      - name: Copy docker-compose and config files
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SERVER_B_HOST }}
#          username: ${{ secrets.SERVER_B_USERNAME }}
#          password: ${{ secrets.SERVER_B_PASSWORD }}
#          source: "docker-compose.yml,ssl/,viva-frontend/nginx.conf"
#          target: "/home/your-username/viva"
#          strip_components: 0

      # 1. 先检查工作目录内容
      - name: List workspace contents
        run: |
          echo "Workspace contents:"
          ls -la
          
      # 2. 复制文件到服务器
      - name: Copy project files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_B_HOST }}
          username: ${{ secrets.SERVER_B_USERNAME }}
          password: ${{ secrets.SERVER_B_PASSWORD }}
          source: "docker-compose.yml,viva-backend/,viva-frontend/"  # 包含所有需要的文件
          target: "/home/lighthouse/viva"
          strip_components: 0

      # 3. SSH 部署
      - name: Deploy to Server B
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_B_HOST }}
          username: ${{ secrets.SERVER_B_USERNAME }}
          password: ${{ secrets.SERVER_B_PASSWORD }}
          script: |
            echo "Starting deployment..."
            
            # 创建目录（如果不存在）
            echo "Creating directory..."
            mkdir -p /home/lighthouse/viva
            
            # 检查目录内容
            echo "Checking directory contents..."
            ls -la /home/lighthouse/viva
            
            # 检查 Docker Compose
            echo "Checking Docker Compose..."
            if ! command -v docker-compose &> /dev/null; then
                echo "Installing Docker Compose..."
                sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            else
                echo "Docker Compose is already installed"
            fi
            
            # 进入项目目录
            echo "Changing to project directory..."
            cd /home/lighthouse/viva || exit 1
            
            # 检查文件
            echo "Listing all files in project directory:"
            ls -la
            
            # 检查 docker-compose.yml 内容
            echo "Checking docker-compose.yml content:"
            cat docker-compose.yml || echo "File not found!"
            
            # 执行部署
            if [ -f "docker-compose.yml" ]; then
                echo "Running Docker Compose commands..."
                docker-compose pull || echo "Pull failed with status: $?"
                docker-compose down || echo "Down failed with status: $?"
                docker-compose up -d || echo "Up failed with status: $?"
            else
                echo "Error: docker-compose.yml not found!"
                exit 1
            fi
            
            echo "Deployment completed" 